import "./globals.css";
import type { Metadata } from "next";
import {  Open_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";



export const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-OpenSans",
});

const metadata: Metadata = {
  title: "Xerocode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
    <html lang="en">
      <body>
      
        <Toaster />
        {children}
      </body>
    </html>
  );
}
